import React from 'react';

const Ranks = () => {
    return(
        <div>
        <p>Cupcake ipsum dolor sit amet carrot cake. Wafer ice cream cookie donut bear claw. Icing fruitcake lemon drops fruitcake sweet cupcake. Croissant cake pie. Carrot cake caramels jelly tart pie. Brownie carrot cake biscuit muffin halvah. I love chupa chups macaroon cupcake bear claw pudding. Ice cream cake donut I love muffin jelly-o bear claw halvah. Sugar plum toffee marzipan tiramisu macaroon bonbon. Wafer I love sugar plum. Dragée chocolate bar ice cream powder chocolate jujubes. Marshmallow cotton candy sweet lollipop chocolate bar. Jelly pudding chupa chups sugar plum bonbon chocolate bar fruitcake ice cream. Lollipop chocolate bar I love oat cake.</p>
        <p>Jujubes cupcake apple pie liquorice tootsie roll pudding jujubes pastry. Tart candy canes jelly pudding. Sugar plum candy canes croissant macaroon. Caramels I love gummi bears. Jelly sweet tootsie roll croissant jelly beans. Fruitcake halvah marzipan cake croissant dragée lollipop muffin brownie. Sugar plum pie jelly sesame snaps sugar plum gummi bears I love marzipan. Soufflé apple pie fruitcake I love. Toffee donut topping jujubes cookie danish. Dessert pie jujubes oat cake biscuit bonbon cotton candy. Topping lollipop pudding carrot cake danish jelly. Caramels chocolate cake danish donut soufflé I love. Topping chupa chups marshmallow soufflé I love.</p>
        <p>Jujubes sesame snaps brownie pudding croissant dragée. Cupcake chocolate bar chocolate chocolate tart jelly lollipop. Danish jelly beans tootsie roll tiramisu bonbon danish. Cake candy canes lemon drops bonbon tootsie roll. Gummies I love gummi bears candy canes cake fruitcake chupa chups chocolate cake liquorice. Jelly I love sweet sugar plum liquorice. Gummies jelly-o icing dessert danish cake cake. Caramels soufflé I love sweet roll gummi bears tiramisu sesame snaps topping gingerbread. Gingerbread danish cotton candy fruitcake. Pie lemon drops chupa chups croissant biscuit pastry powder gummi bears. Fruitcake powder apple pie powder jelly beans tiramisu chocolate bar dessert. Cotton candy biscuit bonbon fruitcake muffin. Fruitcake dessert I love jelly-o muffin dragée. I love pastry fruitcake jujubes cookie lollipop cheesecake.</p>
        <p>Sesame snaps brownie chocolate cake croissant. Candy I love toffee candy canes. Gingerbread croissant sesame snaps marshmallow gummies sesame snaps. Cake sesame snaps liquorice chocolate chocolate chocolate bar tiramisu liquorice. Toffee bear claw danish marzipan biscuit I love candy dragée pastry. Pudding I love pudding lemon drops ice cream. Chupa chups biscuit gummies. Cheesecake icing icing cotton candy. I love toffee apple pie carrot cake croissant fruitcake tart. Jelly-o chupa chups ice cream chocolate oat cake cookie gummies sweet roll lollipop. Cookie cake macaroon sesame snaps danish caramels croissant powder ice cream. Ice cream macaroon jelly candy cupcake. Soufflé sugar plum bear claw macaroon.</p>
        <p>I love chupa chups liquorice fruitcake chocolate. Tootsie roll cotton candy fruitcake croissant I love biscuit marzipan bear claw biscuit. Macaroon soufflé chocolate cake topping powder donut cheesecake gummi bears muffin. Jelly beans sweet roll topping carrot cake. Candy canes sugar plum tootsie roll. Carrot cake croissant halvah tart sesame snaps. Liquorice tart biscuit bear claw. Lemon drops I love topping chupa chups cupcake. Pastry sweet roll chocolate bar sugar plum chupa chups halvah pie chocolate cake pastry. Pie gummi bears cookie bear claw carrot cake apple pie I love. Tootsie roll cookie candy canes jelly sweet lemon drops. Lollipop I love oat cake sweet jelly I love bear claw.</p>
        </div>
    )
}

export default Ranks;